# Generated by Django 2.1.2 on 2018-11-07 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_birth_date', models.DateField(blank=True)),
                ('owner_ps_address', models.TextField()),
                ('owner_pm_address', models.TextField()),
                ('owner_is_active', models.BooleanField(default=False)),
                ('owner_is_approved', models.BooleanField(default=False)),
                ('owner_is_online', models.BooleanField(default=False)),
                ('owner_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerStoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_store_name', models.CharField(max_length=100)),
                ('owner_store_lcs_type', models.CharField(max_length=45)),
                ('owner_store_address', models.TextField()),
                ('owner_store_type', models.CharField(choices=[('General Store', 'gn_store'), ('Pharmacy Store', 'ph_store'), ('Chain Shop', 'ch_store'), ('Sports Shop', 'sp_store')], default='General Store', max_length=40)),
                ('owner_store_is_approved', models.BooleanField(default=False)),
                ('owner_store_is_online', models.BooleanField(default=False)),
                ('owner_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.OwnerModel')),
            ],
        ),
    ]
