# Generated by Django 2.1.2 on 2018-11-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownermodel',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='ownerstoremodel',
            name='owner_store',
        ),
        migrations.DeleteModel(
            name='OwnerModel',
        ),
        migrations.DeleteModel(
            name='OwnerStoreModel',
        ),
    ]
