# Generated by Django 2.1.2 on 2018-11-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_ownermodel_ownerstoremodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownermodel',
            name='owner_profile_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownerstoremodel',
            name='owner_store_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ownerstoremodel',
            name='owner_store_type',
            field=models.CharField(choices=[('gn_store', 'General Store'), ('ph_store', 'Pharmacy Store'), ('ch_store', 'Chain Shop'), ('sp_store', 'Sports Shop')], default='gn_store', max_length=40),
        ),
    ]
