# Generated by Django 2.1.2 on 2018-11-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_auto_20181107_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerstoremodel',
            old_name='owner_store_submitted',
            new_name='owner_store_profile_submitted',
        ),
    ]
